# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('title', models.CharField(max_length=256)),
                ('author', models.CharField(max_length=256)),
                ('blurb', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('deal_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('word', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('lease_name', models.CharField(max_length=256)),
                ('as_of', models.CharField(max_length=7)),
                ('loan_name', models.CharField(max_length=256)),
                ('property_name', models.CharField(max_length=256)),
                ('expiration', models.DateField()),
                ('loanexp', models.DecimalField(max_digits=4, decimal_places=2)),
                ('exposure_usd', models.IntegerField()),
                ('square_feet', models.IntegerField()),
                ('loan_mat_dt', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('loan_name', models.CharField(max_length=256)),
                ('percent_deal', models.DecimalField(max_digits=4, decimal_places=2)),
                ('percent_deal_cutoff', models.DecimalField(max_digits=4, decimal_places=2)),
                ('status', models.CharField(max_length=32)),
                ('status_history', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=5)),
                ('msa', models.CharField(max_length=64)),
                ('property_type', models.CharField(max_length=64)),
                ('property_subtype', models.CharField(max_length=64)),
                ('num_properties', models.IntegerField()),
                ('units', models.IntegerField()),
                ('units_type', models.CharField(max_length=32)),
                ('year_built', models.CharField(max_length=7)),
                ('cum_mo_dq', models.IntegerField()),
                ('cpn', models.DecimalField(max_digits=4, decimal_places=2)),
                ('cutoff_cpn', models.DecimalField(max_digits=4, decimal_places=2)),
                ('rate_type', models.CharField(max_length=16)),
                ('protection', models.CharField(max_length=32)),
                ('due', models.DateField()),
                ('maturity_type', models.CharField(max_length=16)),
                ('amort_type', models.CharField(max_length=16)),
                ('curr_trust_bal_usd', models.IntegerField()),
                ('curr_wh_ln_bal_usd', models.IntegerField()),
                ('cur_bal_per_unit_usd', models.IntegerField()),
                ('orig_trust_bal_usd', models.IntegerField()),
                ('original_bal_usd', models.IntegerField()),
                ('cutoff_trust_bal_usd', models.IntegerField()),
                ('cutoff_bal_per_unit_usd', models.IntegerField()),
                ('scheduled_balloon_usd', models.IntegerField()),
                ('recent_val_usd', models.IntegerField()),
                ('recent_val_dt', models.DateField()),
                ('orig_amortization', models.IntegerField()),
                ('change_in_noi', models.DecimalField(max_digits=5, decimal_places=2)),
                ('ltv', models.IntegerField()),
                ('curr_occ', models.IntegerField()),
                ('dscr', models.DecimalField(max_digits=4, decimal_places=2)),
                ('curr_debt_yld', models.DecimalField(max_digits=4, decimal_places=2)),
                ('noi_start_dt', models.DateField()),
                ('noi_end_dt', models.DateField()),
                ('rec_noi_usd', models.IntegerField()),
                ('rev_ytd_usd', models.IntegerField()),
                ('occ_ytd_usd', models.IntegerField()),
                ('noi_ytd_usd', models.IntegerField()),
                ('dscr_noi_ytd', models.DecimalField(max_digits=4, decimal_places=2)),
                ('rev_py_usd', models.IntegerField()),
                ('occ_py', models.IntegerField()),
                ('noi_py_usd', models.IntegerField()),
                ('dscr_noi_py', models.DecimalField(max_digits=4, decimal_places=2)),
                ('rev_spy_usd', models.IntegerField()),
                ('occ_spy', models.IntegerField()),
                ('noi_spy_usd', models.IntegerField()),
                ('dscr_noi_spy', models.DecimalField(max_digits=4, decimal_places=2)),
                ('cutoff_dscr', models.DecimalField(max_digits=4, decimal_places=2)),
                ('cutoff_debt_yld', models.DecimalField(max_digits=4, decimal_places=2)),
                ('cutoff_noi_usd', models.IntegerField()),
                ('cutoff_ncf_usd', models.IntegerField()),
                ('cutoff_ltv', models.IntegerField()),
                ('cutoff_occ', models.IntegerField()),
                ('largest_tenant', models.CharField(max_length=128)),
                ('lrg_tenant_pct', models.DecimalField(max_digits=4, decimal_places=2)),
                ('lrg_tenant_exp_dt', models.DateField()),
                ('second_largest_tenant', models.CharField(max_length=128)),
                ('second_lrg_tenant_pct', models.DecimalField(max_digits=4, decimal_places=2)),
                ('second_lrg_tenant_exp_dt', models.DateField()),
                ('third_lrg_tenant_exp_dt', models.DateField()),
                ('third_lrg_tenant_pct', models.DecimalField(max_digits=4, decimal_places=2)),
                ('third_largest_tenant', models.CharField(max_length=128)),
                ('fourth_lrg_tenant_exp_dt', models.DateField()),
                ('fourth_lrg_tenant_pct', models.DecimalField(max_digits=4, decimal_places=2)),
                ('fourth_largest_tenant', models.CharField(max_length=128)),
                ('fifth_lrg_tenant_exp_dt', models.DateField()),
                ('fifth_lrg_tenant_pct', models.DecimalField(max_digits=4, decimal_places=2)),
                ('fifth_largest_tenant', models.CharField(max_length=128)),
                ('originator', models.CharField(max_length=128)),
                ('origination_dt', models.DateField()),
                ('collateral_id', models.IntegerField()),
                ('trustee_id', models.IntegerField()),
                ('link_ID', models.CharField(max_length=64, serialize=False, primary_key=True)),
                ('deal', models.ForeignKey(to='cmbs.Deal')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('property_name', models.CharField(max_length=256)),
                ('uw', models.CharField(max_length=256)),
                ('loan_name', models.CharField(max_length=128)),
                ('loan_status', models.CharField(max_length=32)),
                ('property_type', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=256)),
                ('city', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=5)),
                ('msa', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=74)),
                ('appraisal_value_usd', models.IntegerField()),
                ('value_as_of', models.DateField()),
                ('cutoff_value_usd', models.IntegerField()),
                ('occ', models.IntegerField()),
                ('occ_as_of', models.DateField()),
                ('cutoff_occ', models.IntegerField()),
                ('cap_rate', models.DecimalField(max_digits=4, decimal_places=2)),
                ('cutoff_noi_usd', models.IntegerField()),
                ('noi_usd', models.IntegerField()),
                ('noi_as_of', models.DateField()),
                ('cutoff_ncf_usd', models.IntegerField()),
                ('ncf_usd', models.IntegerField()),
                ('ncf_as_of', models.DateField()),
                ('curr_sqft_units', models.IntegerField()),
                ('cutoff_sqft_units', models.IntegerField()),
                ('curr_alloc_amt_usd', models.IntegerField()),
                ('curr_alloc_pct', models.IntegerField()),
                ('fin_indic', models.CharField(max_length=4)),
                ('def_maintenance', models.CharField(max_length=1)),
                ('loan_trustee_id', models.CharField(max_length=32)),
                ('year_built', models.CharField(max_length=4)),
                ('year_renovated', models.CharField(max_length=4)),
                ('lease_review_dt', models.DateField()),
                ('lease_r_o_1st_yr', models.IntegerField()),
                ('lease_r_o_2nd_yr', models.IntegerField()),
                ('lease_r_o_3rd_yr', models.IntegerField()),
                ('lease_r_o_4th_yr', models.IntegerField()),
                ('lease_r_o_5th_yr', models.IntegerField()),
                ('reo_comm', models.TextField()),
                ('reo_comm_asof', models.DateField()),
                ('deal', models.ForeignKey(to='cmbs.Deal')),
                ('loan_link', models.ForeignKey(to='cmbs.Loan')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, primary_key=True, auto_created=True)),
                ('name', models.CharField(max_length=256)),
                ('articles_searched', models.IntegerField()),
                ('relevant_found', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lease',
            name='loan_link',
            field=models.ForeignKey(to='cmbs.Loan'),
        ),
        migrations.AddField(
            model_name='articles',
            name='key_words',
            field=models.ManyToManyField(to='cmbs.Keywords'),
        ),
        migrations.AddField(
            model_name='articles',
            name='publisher_ID',
            field=models.ForeignKey(to='cmbs.Publisher'),
        ),
    ]
